#!/bin/bash

brightness=$(cat /sys/class/backlight/intel_backlight/brightness)
max_brightness=$(cat /sys/class/backlight/intel_backlight/max_brightness)

case $1 in
    +)let brightness=$brightness+1 ;;
    -)let brightness=$brightness-1 ;;
    *)exit ;;
esac

# Prevent going fully off or over max.
if (($brightness > 0)) && (($brightness <= $max_brightness)); then
    echo "echo $brightness > /sys/class/backlight/intel_backlight/brightness" | sudo bash
fi
