#!/usr/bin/env bash

count=$(checkupdates | wc -l)
# countaur=$(pacaur -k | grep 'ignored' -v | wc -l)
output="   $count"

available="#81A2BE"
warning="#DE935F"
crit="#A54242"

if (( count > 30 )); then
    echo "<span foreground=\"$crit\">$output</span>"
elif (( count > 20 )); then
    echo "<span foreground=\"$warning\">$output</span>"
elif (( count > 5 )); then
    echo "<span foreground=\"$available\">$output</span>"
fi
