#!/usr/bin/env bash

count=$(checkupdates | wc -l)
output="   $count"

available="#8ABEB7"
warning="#DE935F"
crit="#A54242"

if (( count > 25 )); then
    echo "<span foreground=\"$crit\">$output</span>"
elif (( count > 15 )); then
    echo "<span foreground=\"$warning\">$output</span>"
elif (( count > 3 )); then
    echo "<span foreground=\"$available\">$output</span>"
fi
